name: Generate Package
on: 
  create:
    tags:
     - v*
jobs:
  Create-Package:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: install nox
        uses: daisylb/setup-nox@v2.1.0
      - name: Create new release
        run: |
          nox -e package
      - name: Archive package
        uses: actions/upload-artifact@v2
        with:
          path: |
            dist/*