name: Run Tests
on: [push]
jobs: 
  Run-Tests:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.8", "3.9", "3.10"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: install python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: install nox
        uses: daisylb/setup-nox@v2.1.0
      - name: Run tests
        run: |
          nox -e test
          nox -e cov_report
      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: |
            coverage.xml
      - name: Upload coverage
        uses: codecov/codecov-action@v2
        with:
          files: ./coverage.xml
          fail_ci_if_error: true
          verbose: true
      - name: Check code quality
        run: |
          nox -e quality